In [2]:
import numpy as np

In [10]:
"""
Numpy Array Attributes
"""

# Creating an array
print(np.arange(3))
print(np.arange(3, 9))
print(np.arange(3, 9, 2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [31]:
# Random number generator

np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
print(arr)

print("arr.ndim =", arr.ndim)
print("arr.shape =", arr.shape)
print("arr.size =", arr.size)

print("arr.dtype =", arr.dtype)
print("arr.itemsize =", arr.itemsize)
print("arr.nbytes =", arr.nbytes)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
arr.ndim = 2
arr.shape = (3, 4)
arr.size = 12
arr.dtype = int32
arr.itemsize = 4
arr.nbytes = 48


In [34]:
"""
Slicing
"""

arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [45]:
# Multi-dimenstional Subarrays
np.random.seed(2)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]


In [46]:
"""
Subarrays as Views
"""


np.random.seed(3)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]
[[8 9]
 [9 9]]
[[99  9]
 [ 9  9]]
[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]


In [50]:
"""
Reshaping of Arrays
"""

arr = np.arange(1,10)
print(arr, '\n')

grid = arr.reshape(3, 3)
print(grid, '\n')


[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [52]:
# np.newaxis

arr_new = arr[np.newaxis, :] 
print(arr_new)
print(arr_new.shape, '\n')

arr_new = arr[:, np.newaxis]
print(arr_new)
print(arr_new.shape, '\n')

[[1 2 3 4 5 6 7 8 9]]
(1, 9) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1) 



In [63]:
"""
Array Concatenation
"""
arr_1 = np.array([[1, 2, 3], [1, 2, 3]])
arr_2 = np.array([[4, 5, 6], [4, 5, 6]])
arr_3 = np.array([[7, 8, 9], [7, 8, 9]])

arr_total = np.concatenate([arr_1, arr_2, arr_3], axis=1)
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [64]:
"""
Array Spliting
"""

arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr, '\n')

arr_1, arr_2 = np.split(arr, [4])
print(arr_1, arr_2)


[1, 2, 3, 99, 99, 3, 2, 1] 

[ 1  2  3 99] [99  3  2  1]
