In [3]:
import numpy as np

In [4]:
"""
Computiong reciprocals in loops
"""

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size = 5)
print(values)

compute_reciprocals(values)

[6 6 6 7 8]


array([0.16666667, 0.16666667, 0.16666667, 0.14285714, 0.125     ])

In [11]:
"""
Comprarison: Loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1, 100, size=1000000)

# Looping on a big array
%timeit compute_reciprocals(big_array)

# magic function (e, g., %timeit)

1.75 s ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
# Vectorized operations
%timeit 1 / big_array

1.74 ms ± 5.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3,5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)


[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [63]:
"""
UFuncs: Array Arithemtic
"""

x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 5 =", x * 5)
print("x / 5 =", x / 5)
print("x ** 5 =", x ** 5)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 5 = [ 0  5 10 15]
x / 5 = [0.  0.2 0.4 0.6]
x ** 5 = [  0   1  32 243]


In [23]:
"""
UFuncs: Absolute Value
"""

x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [27]:
"""
UFuncs: Trigonomeric Funcitons
"""

theta = np.linspace(0, np.pi, 3)
print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [45]:
"""
UFuncs: Aggregation
"""

x = np.arange(1, 5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [48]:
# accumulat()

x = np.arange(1, 15)
print(x)

accum = np.multiply.accumulate(x)
print(accum)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [51]:
# Summing the Values in an Array

np.random.seed(2)
arr = np.random.rand(1000000) # rand(): create 0~1 real values

print(arr)
print('sum =', np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.78483191 0.00778062 0.42442656]
sum = 499468.5166853333
77.7 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [53]:
%timeit np.sum(arr)

301 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [57]:
# Other Aggr. functions
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 90))
print(np.any(arr>1))
print(np.all(arr>0))

max = 0.9999976661165695
min = 9.475783189216713e-07
mean = 0.49946851668533326
median = 0.49948650836352526
percentile = 0.9004310892470595
False
True


In [61]:
# Multi dimensioal aggregates

np.random.seed(5)

arr = np.random.randint(10, size=(3,4))
print(arr)

print(np.sum(arr, axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[15 28  8]
